---

- name: (gitlab_config) [1/1] Template /etc/gitlab/gitlab.rb is deployed
  template:
    src: ../templates/gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart httpd
    - Reconfigure gitlab
    - Restart gitlab
